### ISSUE TITLE
Implement Threshold SHA256 fullfilment

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/java-crypto-conditions#13]

**Comment by koekiebox** [comment]
I need a description here @adrianhopebailie .

**Comment by adrianhopebailie** [comment]
We need to implement the THRESHOLD-SHA-256 type of fulfillment.

See the spec: https://github.com/interledger/rfcs/blob/master/0002-crypto-conditions/0002-crypto-conditions.md#threshold-sha-256-threshold-sha-256-condition-type

The current code only implements the other types.
