### ISSUE TITLE
pom file is broken

### ISSUE THREAD

**Issue by mgrand** [interledger/java-crypto-conditions#35]
The java does not compile because it uses lambda expressions and the pom has

    <maven.compiler.source>1.6</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.target>1.6</maven.compiler.target>

Please change 1.6 to 1.8.

**Comment by andrew-g-za** [comment]
Looks like this was fixed in e0c6cd94f1c1b125f521ef5d00f2c4b9a7a0804e 16 Jan 2017
