### ISSUE TITLE
Change versioning as a precursor to initial Maven Central deploy

### ISSUE THREAD

**Issue by sappenin** [interledger/java-crypto-conditions#45]
As we lay the groundwork for deploying our first CryptoCondition artifacts to [Maven Central](https://search.maven.org/), I propose that we adjust the versioning of this library to something below `1.0.0` until the official 1.0 version of the spec is released.

Rationale #1: The library isn't quite ready for a "1.0" because the Crypto-Condition [spec](https://tools.ietf.org/html/draft-thomas-crypto-conditions-02) itself is still a "draft", currently sitting at draft 2.  Ideally, we wouldn't release a `1.0.x` of CryptoConditions jars/artifacts until we have a stable spec.

Rationale #2: One might think we should align the CC library versions (currently 2.0.0-SNAPSHOT) with the draft spec versions (currently 2), but IMHO this is ill-advised.  For example, imagine that the CC spec goes through 13 more drafts -- we would then potentially have a Java library sitting at version 15.0.0, which feels odd.  

Instead, I propose that we version the library as follows:

* While the CC Spec is in draft, our `version.major` should be 0, and our `version.minor` should match the draft number.  Finally, our `version.patch` should increment whenever we have a new draft-2 change in the library.  As an example, the current version should be `0.2.0`.  If we fix some code, and decide a release is warranted, then we would have a new version of `0.2.1`, and so on.
* When draft-3 of the CC spec is released, any code that implements that spec should be released under the version `0.3.x`.
* When the CryptoCondition spec is accepted, we should then have various Java artifacts implementing that spec using a  a series of `1.0.x` releases.

Thoughts?

**Comment by andrew-g-za** [comment]
totally agreed, it makes the most sense.

**Comment by adrianhopebailie** [comment]
Makes sense to me
