### ISSUE TITLE
Serializing Fulfillment

### ISSUE THREAD

**Issue by ManujSubhankar** [interledger/java-crypto-conditions#65]
Ed25519Sha256Fulfillment doesn't implement Serializable. How can we write Ed25519Sha256Fulfillment object into a file and read it back. There is an getEncoded() function. But how to decode?

**Comment by sappenin** [comment]
Hi @ManujSubhankar, the getEncoded() function will return a byte[] (array of bytes). If you want to read these bytes, you can use CryptoConditionReader.readFulfillment() to reverse the process.
