### ISSUE TITLE
Fix Condition Constructor modifiers

### ISSUE THREAD

**Issue by sappenin** [interledger/java-crypto-conditions#74]
See [this comment](https://github.com/interledger/java-crypto-conditions/pull/73/files#r145783281) for more details, but we should inspect the Constructor of each Condition and make sure it's modifier is correct. For example, in `PreimageSha256` in the PR linked above, the public constructor should be package-private, and the package-private constructor should be public.

**Comment by adrianhopebailie** [comment]
Fixed for PreimageSha256 in #73

**Comment by sappenin** [comment]
For future: I think only half was fix by #73 - we still need to make the other public modifier package-private (likely).
